# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J2lkim3YeGKAv5O-R4p3oMSj1HjFvyR_
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

import  warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/titanic.csv')
df.head()

df.shape

df.info()

sns.heatmap(df.isnull())

df.describe()

df.drop(['PassengerId','Name','Cabin','Ticket'],axis=1,inplace=True)

df.head()

sns.boxplot(x='Pclass',y='Age',data=df)

def fill_age(cols):
  Age = cols[0]
  Pclass = cols[1]
  if pd.isnull(Age):
    if Pclass == 1:
      return 41
    elif Pclass ==2:
      return 29
    elif Pclass == 3:
      return 25
    else:
      return Age

df['Age'] = df[['Age','Pclass']].apply(fill_age,axis=1)

df.dropna(inplace=True)

sns.heatmap(df.isnull())

sns.violinplot(x='Sex',y='Survived',hue='Pclass',data=df)

df['Survived'].value_counts().plot(kind='pie',autopct='%0.1f%%')

df.head()

df.info()

object = ['Sex','Embarked']
for columns in object:
  df[columns] = df[columns].astype('category')

df.info()

sex = pd.get_dummies(df['Sex'],drop_first=True,dtype=int)
embark = pd.get_dummies(df['Embarked'],drop_first=True,dtype=int)

df = pd.concat([df,sex,embark],axis=1)

df.info()

df.head()

df.drop(['Sex','Embarked'],axis=1,inplace=True)

df.head()

x = df.drop('Survived',axis=1)
y = df['Survived']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=101)

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(x_train,y_train)

pre = lr.predict(x_test)
print(pre)

from sklearn.metrics import  accuracy_score

print('Classification:')
print('------'*30)
result = round(accuracy_score(y_test,pre)*100,2)
print('Accuracy Score:',result,'%')

input = [[2,30.0,1,1,13.0000,1,1,0]]
predict = lr.predict(input)
print(predict)

