# -*- coding: utf-8 -*-
"""Linear Regresion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TeTOPVMBvK7rujvUM7xkCUq8PGPyYrkY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('/content/Housing.csv')

df.head()

df.shape

sns.heatmap(df.isnull())

df.info()

df.drop(['parking','airconditioning','basement','stories','furnishingstatus','hotwaterheating'],axis=1,inplace=True)

df.head()

df.describe()

sns.displot(x='bedrooms',data=df,kde=True)

df['mainroad'].value_counts().plot(kind='pie',autopct='%0.1f%%')

df.info()

object = ['mainroad','guestroom','prefarea']
for columns in object:
  df[columns] =  df[columns].astype('category')

df.info()

mainroad = pd.get_dummies(df['mainroad'],drop_first=True,dtype=int)
guestroom = pd.get_dummies(df['guestroom'],drop_first=True,dtype=int)
prefarea = pd.get_dummies(df['prefarea'],drop_first=True,dtype=int)

df = pd.concat([df,mainroad,guestroom,prefarea],axis=1)

df.head()

df.drop(['mainroad','guestroom','prefarea'],axis=1,inplace=True)

df.head()

x = df.drop(['price'],axis=1)

y=df['price']

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=101)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)

pre = lr.predict(x_test)

print(pre)

sns.scatterplot(x=y_test,y=pre,color='blue',label='Actual Data')
plt.plot([min(y_test),max(y_test)],[min(y_test),max(y_test)],color='red',label='Data Point')
plt.legend()
plt.show()

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test,pre)
abs = np.sqrt(mse)
print('MSE: ',mse)
print('ABS: ',abs)