# -*- coding: utf-8 -*-
"""Ml propertys.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NvrffbMn6jwLaOL5WjUe_3Es-Y3ezMvd
"""

import  pandas as pd ## it is open source python library which is use for data maiploation and analysis. It is  well sutabile for working
#with tabular data such as spread sheets or SQL table.
import numpy as np ##Numpy is an open source mathematical and scientific compputer library  for computer  programming task

df = pd.read_csv('/content/titanic.csv')

df.head() #head show me  the  firt 5 rows

df.shape #it tell me how many row and columns in my dataset

df.isnull().sum() #It show me the missing value in our data

df.describe() #It describe the maen std max in the numarical value

df.info() #It tell the information for all of all our columns and also tell the datatype and use how many memory use

df.drop(['Name'],axis=1,inplace =True)#It  drop the unusuall value for our dataset

df['Sex'].value_counts()

