# -*- coding: utf-8 -*-
"""Student Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zetx-qSaC9IV1DOLegvqT9m66KC8eoU-
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
import warnings

df = pd.read_csv('/content/student_exam_scores.csv')
df.head()

df.info()

df.shape

sns.heatmap(df.isnull())

df.drop('student_id',axis=1,inplace=True)

df.head()

x = df.drop('exam_score',axis=1)
y=df['exam_score']

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error,r2_score
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

lr = LinearRegression()
lr.fit(x_train_scaled,y_train)

pre = lr.predict(x_test_scaled)

r2_score(y_test,pre)

import joblib

model = joblib.dump(lr,'model.pkl')
scale = joblib.dump(scaler,'scaler.pkl')

