# -*- coding: utf-8 -*-
"""Visualization Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XeE_g_qgXVw3MUn0mNwBxOe6f6WEeBxj
"""

import pandas as pd
import numpy as np
import  matplotlib.pyplot as plt
import seaborn as sns

df1 = pd.read_csv('/content/titanic.csv')

df1.head()

sns.barplot(x='Pclass',y='Survived',data=df1)

sns.boxplot(x='Pclass',y='Age',data=df1)

df = pd.read_csv('/content/tips.csv')

df.head(

)

"""#Relational Plot"""

sns.relplot(data=df,x='total_bill',y='tip',hue='day')

"""#Scatter Plot

"""

sns.scatterplot(data=df,x='total_bill',y='tip',hue='sex')

"""#Distribution Plot

"""

sns.displot(data=df,x='total_bill',kde=True)

"""#Kde plot"""

sns.kdeplot(data=df,x='tip')

"""#Categorical Plot"""

sns.catplot(x='total_bill',y='day',data=df)

"""#Box plot"""

sns.catplot(x='tip',y='smoker',data=df,kind='box')

sns.boxplot(x='tip',data=df)

sns.boxplot(x='sex',y='total_bill',hue='smoker',fill=False,gap=.1,data=df)

sns.violinplot(x='tip',data=df)

"""#Violinplot"""

sns.violinplot(x='time',y='sex',hue='smoker',fill=False,gap=.1,data=df)

